# Generated by Django 5.1.1 on 2024-09-26 12:29

import contracts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_start_date'),
        ('products', '0002_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(null=True, upload_to=contracts.models.contract_directory_path),
        ),
        migrations.AddField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
