# Generated by Django 5.1.1 on 2024-10-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
