# Generated by Django 5.1.1 on 2024-09-23 13:36

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU'),
        ),
    ]
