# Generated by Django 5.1.1 on 2024-09-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('leads', '0004_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.ads'),
        ),
    ]
